- hosts: all
  remote_user: pi
  vars_files:
    - provision-vars.yml
  vars:
    ansible_ssh_private_key_file: "{{ provision_ssh_private_key }}"
  tasks:
    - debug: msg="Ansible running in {{ ansible_lsb.id }}!"
    - name: Echo a hello message
      command: echo hello
